import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const APPS = [];

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Animations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul>
          <Link href={"/apps/hero-animation"}>
            <a>Hero animation</a>
          </Link>
        </ul>
      </main>
    </div>
  );
};

export default Home;
